# Generated by Django 5.1.4 on 2024-12-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE')),
                ('especialidad', models.CharField(max_length=100, verbose_name='ESPECIALIDAD')),
            ],
        ),
    ]
