# Generated by Django 5.1.4 on 2024-12-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0004_cliente_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='especialidad',
            field=models.CharField(max_length=100, verbose_name='ESPECIALIDAD'),
        ),
    ]
