# Generated by Django 5.1.4 on 2024-12-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0006_empleados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
    ]
