# Generated by Django 5.1.4 on 2024-12-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0009_alter_empleado_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='password',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='user',
        ),
    ]
