# Generated by Django 5.1.4 on 2024-12-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0010_remove_empleado_password_remove_empleado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='especialidad',
        ),
    ]
