# Generated by Django 5.1.4 on 2024-12-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0011_remove_cliente_especialidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
