# Generated by Django 5.1.4 on 2024-12-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0012_delete_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='especialidad',
            field=models.CharField(default='UNKNOWN', max_length=20, verbose_name='ESPECIALIDAD'),
        ),
    ]
