# Generated by Django 5.1.4 on 2024-12-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0013_cliente_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='especialidad',
            field=models.CharField(max_length=20, verbose_name='ESPECIALIDAD'),
        ),
    ]
