# Generated by Django 5.1.4 on 2024-12-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stremio', '0014_alter_cliente_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreE', models.CharField(max_length=100, verbose_name='NOMBRE')),
                ('cedula', models.CharField(max_length=100, verbose_name='CURP')),
                ('especialidad', models.CharField(max_length=20, verbose_name='ESPECIALIDAD')),
            ],
        ),
    ]
